const quotes = [
    " Every day is a fresh start.",
    " You are stronger than you think.",
    " Small steps still move you forward.",
    " It's okay to not be okay",
    " You don't have to have it all figured out.",
    " Progress, not perfection.",
    " Be kind to yourself today.",
    " You've survived 100% of your hard days so far.",
    " Rest is productive too.",
    " Your feelings are valid.",
    " One step at a time is still moving forward.",
    " You matter more than you know.",
    " Difficult roads often lead to beautiful destinations.",
    " Asking for help is a sin of strength.",
    " You are not alone in this.",
    " Take it one breath at a time.",
    " Your best is always enough.",
    " Better days are coming.",
    " Be patient with yourself.",
    " You are worthy of good things.",
    " Healing is not linear.",
    " Every effort you make counts.",
    " You are doing better than you think.",
    " The secret of getting ahead is getting started.",
    " It does not matter how slowly you go as long as you do not stop.",
    " Believe you can and you're halfway there.",
    " Work hard in silence, let sucess be your noise.",
    " If you fell down yesterday, stand up today.",
    " If you can dream it, you can do it.",
    " Your journey is unique- embrace it.",
    " Keep going- you've got this.",
    " Storms don't last forever- keep going.",
    " You are not your worst day.",
    " Growth happens outside of your comfort zone.",
    " Even the darkest night will end and the sun will rise.",
    " You are allowed to outgrow things that no longer serve you.",
    " Your mental health is just as important as your physical health.",
    " Celebrate every small win- they all count.",
    " You are not behind in life, you are on your own path.",
    " It's okay to feel overwhelmed- take a breath and reset.",
    " The fact that you're trying is already something to be proud of.",

];


